export const GET_HE_THONG = "GET_HE_THONG";
export const GET_HE_THONG_SUCCESS = "GET_HE_THONG_SUCCESS";
export const GET_HE_THONG_FAILED = "GET_HE_THONG_FAILED";

export const GET_THONG_TIN_CUM_RAP_THEO_HE_THONG_SUCCESS =
  "GET_THONG_TIN_CUM_RAP_THEO_HE_THONG_SUCCESS";
export const GET_THONG_TIN_CUM_RAP_THEO_HE_THONG_FAILED =
  "GET_THONG_TIN_CUM_RAP_THEO_HE_THONG_FAILED";
